services:
  reverse-proxy:
    env_file:
      - ./.env.local

  frontend:
    command: npm run dev
    env_file:
      - ./.env.local
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
      - /app/.next

  game:
    command: npm run dev
    env_file:
      - ./.env.local
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/game:/app
      - /app/node_modules

  document-content-api:
    env_file:
      - ./.env.local
    networks:
      - services-network

  document-content-grpc:
    env_file:
      - ./.env.local

  document-content-ocr-coordinator:
    container_name: document-content-ocr-coordinator
    hostname: document-content-ocr-coordinator
    build:
      context: ./services/document-content/src/worker
      dockerfile: ocr_coordinator/Dockerfile
    image: document-content-ocr-coordinator:latest
    command: python -m ocr_coordinator.worker
    env_file:
      - ./.env.local
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - services-network

  document-content-indexing-worker:
    container_name: document-content-indexing-worker
    hostname: document-content-indexing-worker
    build:
      context: ./services/document-content/src/worker
      dockerfile: indexing_worker/Dockerfile
    image: document-content-indexing-worker:latest
    command: python -m indexing_worker.worker
    env_file:
      - ./.env.local
    volumes:
      - ./services/document-content/output:/output
      - ./services/document-content/temp:/temp
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - services-network

  game-service:
    env_file:
      - ./.env.local

  game-generation-worker:
    env_file:
      - ./.env.local

  user-service:
    env_file:
      - ./.env.local

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    ports:
      - "6379:6379"

volumes:
  models:
