services:
  reverse-proxy:
    env_file:
      - ./.env.local

  frontend:
    command: npm run dev
    env_file:
      - ./.env.local
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
      - /app/.next

  game:
    command: npm run dev
    env_file:
      - ./.env.local
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/game:/app
      - /app/node_modules

  document-content-api:
    env_file:
      - ./.env.local
    networks:
      - services-network

  document-content-grpc:
    env_file:
      - ./.env.local

  document-content-ocr-coordinator:
    env_file:
      - ./.env.local

  document-content-indexing-worker:
    env_file:
      - ./.env.local

  game-service:
    env_file:
      - ./.env.local

  game-generation-worker:
    env_file:
      - ./.env.local

  user-service:
    env_file:
      - ./.env.local

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    ports:
      - "6379:6379"

volumes:
  models:
