services:
  reverse-proxy:
    env_file:
      - ./.env.staging
    restart: unless-stopped

  frontend:
    command: sh -c "npm run build && npm run start"
    env_file:
      - ./.env.staging
    environment:
      NODE_ENV: production
    restart: unless-stopped

  game:
    command: sh -c "npm run build && npm run preview -- --host 0.0.0.0 --port 5173"
    env_file:
      - ./.env.staging
    environment:
      NODE_ENV: production
    restart: unless-stopped

  document-content-api:
    env_file:
      - ./.env.staging
    restart: unless-stopped

  document-content-grpc:
    env_file:
      - ./.env.staging
    restart: unless-stopped

  game-service:
    env_file:
      - ./.env.staging
    restart: unless-stopped

  game-generation-worker:
    env_file:
      - ./.env.staging
    restart: unless-stopped

  user-service:
    env_file:
      - ./.env.staging
    restart: unless-stopped
