services:
  reverse-proxy:
    env_file:
      - ./.env.dev
    restart: unless-stopped

  frontend:
    command: npm run dev
    env_file:
      - ./.env.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

  game:
    command: npm run dev
    env_file:
      - ./.env.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend/game:/app
      - /app/node_modules
    restart: unless-stopped

  document-content-api:
    env_file:
      - ./.env.dev
    restart: unless-stopped

  document-content-grpc:
    env_file:
      - ./.env.dev
    restart: unless-stopped

  document-content-ocr-coordinator:
    env_file:
      - ./.env.dev
    restart: unless-stopped

  document-content-indexing-worker:
    env_file:
      - ./.env.dev
    restart: unless-stopped

  game-service:
    env_file:
      - ./.env.dev
    restart: unless-stopped

  game-generation-worker:
    env_file:
      - ./.env.dev
    restart: unless-stopped

  user-service:
    env_file:
      - ./.env.dev
    restart: unless-stopped
