with-expecter: false
issue-845-fix: true
packages:
  skybloom/document-content-grpc/internal/service:
    config:
      dir: internal/service/mocks
      outpkg: mocks
    interfaces:
      DocumentRepository:
        config:
          filename: document_repository.go
      MarkdownLoader:
        config:
          filename: markdown_loader.go
