FROM golang:1.23-alpine AS dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

CMD ["go", "run", "./cmd/worker"]

FROM golang:1.23-alpine AS builder

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /game-generation-worker ./cmd/worker

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /game-generation-worker /app/game-generation-worker

ENV PORT=8081

CMD ["/app/game-generation-worker"]
