with-expecter: false
issue-845-fix: true
packages:
  skybloom/level-generator-worker/internal/worker:
    config:
      dir: internal/worker/mocks
      outpkg: mocks
    interfaces:
      LevelRepository:
        config:
          filename: level_repository.go
      SourceFetcher:
        config:
          filename: source_fetcher.go
      LevelGenerator:
        config:
          filename: level_generator.go
