// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	generator "skybloom/level-generator-worker/internal/generator"
	source "skybloom/level-generator-worker/internal/source"

	mock "github.com/stretchr/testify/mock"
)

// MockLevelGenerator is an autogenerated mock type for the LevelGenerator type
type MockLevelGenerator struct {
	mock.Mock
}

// GenerateLevel provides a mock function with given fields: ctx, sourceContext
func (_m *MockLevelGenerator) GenerateLevel(ctx context.Context, sourceContext source.SourceContext) (generator.LevelGeneration, error) {
	ret := _m.Called(ctx, sourceContext)

	if len(ret) == 0 {
		panic("no return value specified for GenerateLevel")
	}

	var r0 generator.LevelGeneration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, source.SourceContext) (generator.LevelGeneration, error)); ok {
		return rf(ctx, sourceContext)
	}
	if rf, ok := ret.Get(0).(func(context.Context, source.SourceContext) generator.LevelGeneration); ok {
		r0 = rf(ctx, sourceContext)
	} else {
		r0 = ret.Get(0).(generator.LevelGeneration)
	}

	if rf, ok := ret.Get(1).(func(context.Context, source.SourceContext) error); ok {
		r1 = rf(ctx, sourceContext)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockLevelGenerator creates a new instance of MockLevelGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLevelGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLevelGenerator {
	mock := &MockLevelGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
