// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	generator "skybloom/level-generator-worker/internal/generator"
	repository "skybloom/level-generator-worker/internal/repository"
	source "skybloom/level-generator-worker/internal/source"

	mock "github.com/stretchr/testify/mock"
)

// MockLevelRepository is an autogenerated mock type for the LevelRepository type
type MockLevelRepository struct {
	mock.Mock
}

// Insert provides a mock function with given fields: ctx, sourceContext, generation, model
func (_m *MockLevelRepository) Insert(ctx context.Context, sourceContext source.SourceContext, generation generator.LevelGeneration, model string) (repository.SavedLevel, error) {
	ret := _m.Called(ctx, sourceContext, generation, model)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 repository.SavedLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, source.SourceContext, generator.LevelGeneration, string) (repository.SavedLevel, error)); ok {
		return rf(ctx, sourceContext, generation, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, source.SourceContext, generator.LevelGeneration, string) repository.SavedLevel); ok {
		r0 = rf(ctx, sourceContext, generation, model)
	} else {
		r0 = ret.Get(0).(repository.SavedLevel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, source.SourceContext, generator.LevelGeneration, string) error); ok {
		r1 = rf(ctx, sourceContext, generation, model)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockLevelRepository creates a new instance of MockLevelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLevelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLevelRepository {
	mock := &MockLevelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
