// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	source "skybloom/level-generator-worker/internal/source"

	mock "github.com/stretchr/testify/mock"
)

// MockSourceFetcher is an autogenerated mock type for the SourceFetcher type
type MockSourceFetcher struct {
	mock.Mock
}

// FetchSubChapterContent provides a mock function with given fields: ctx, userID, subChapterID
func (_m *MockSourceFetcher) FetchSubChapterContent(ctx context.Context, userID string, subChapterID string) (source.SourceContext, error) {
	ret := _m.Called(ctx, userID, subChapterID)

	if len(ret) == 0 {
		panic("no return value specified for FetchSubChapterContent")
	}

	var r0 source.SourceContext
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (source.SourceContext, error)); ok {
		return rf(ctx, userID, subChapterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) source.SourceContext); ok {
		r0 = rf(ctx, userID, subChapterID)
	} else {
		r0 = ret.Get(0).(source.SourceContext)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, subChapterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockSourceFetcher creates a new instance of MockSourceFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSourceFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSourceFetcher {
	mock := &MockSourceFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
