// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	uuid "github.com/google/uuid"
	models "skybloom/document-content-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockDocumentStore is an autogenerated mock type for the DocumentStore type
type MockDocumentStore struct {
	mock.Mock
}

// CreateQueuedDocument provides a mock function with given fields: ctx, document
func (_m *MockDocumentStore) CreateQueuedDocument(ctx context.Context, document models.Document) error {
	ret := _m.Called(ctx, document)

	if len(ret) == 0 {
		panic("no return value specified for CreateQueuedDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Document) error); ok {
		r0 = rf(ctx, document)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDocumentCascade provides a mock function with given fields: ctx, documentID, userID
func (_m *MockDocumentStore) DeleteDocumentCascade(ctx context.Context, documentID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, documentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocumentCascade")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, documentID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListUserDocuments provides a mock function with given fields: ctx, userID
func (_m *MockDocumentStore) ListUserDocuments(ctx context.Context, userID uuid.UUID) ([]models.DocumentSummary, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserDocuments")
	}

	var r0 []models.DocumentSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.DocumentSummary, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.DocumentSummary); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DocumentSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadUserDocument provides a mock function with given fields: ctx, documentID, userID
func (_m *MockDocumentStore) LoadUserDocument(ctx context.Context, documentID uuid.UUID, userID uuid.UUID) (models.Document, error) {
	ret := _m.Called(ctx, documentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LoadUserDocument")
	}

	var r0 models.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.Document, error)); ok {
		return rf(ctx, documentID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.Document); ok {
		r0 = rf(ctx, documentID, userID)
	} else {
		r0 = ret.Get(0).(models.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, documentID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockDocumentStore creates a new instance of MockDocumentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentStore {
	mock := &MockDocumentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
