// Code generated by mockery; DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"

	"skybloom/document-content-api/internal/models"
)

type DocumentStore struct {
	mock.Mock
}

func (_m *DocumentStore) CreateQueuedDocument(ctx context.Context, document models.Document) error {
	ret := _m.Called(ctx, document)

	if len(ret) == 0 {
		panic("no return value specified for CreateQueuedDocument")
	}

	if rf, ok := ret.Get(0).(func(context.Context, models.Document) error); ok {
		return rf(ctx, document)
	}

	return ret.Error(0)
}

func (_m *DocumentStore) ListUserDocuments(ctx context.Context, userID uuid.UUID) ([]models.DocumentSummary, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserDocuments")
	}

	var r0 []models.DocumentSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.DocumentSummary); ok {
		r0 = rf(ctx, userID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.DocumentSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *DocumentStore) ListPublicGames(ctx context.Context, userID uuid.UUID, cursor string) (models.ListGameLibraryResponse, error) {
	ret := _m.Called(ctx, userID, cursor)

	if len(ret) == 0 {
		panic("no return value specified for ListPublicGames")
	}

	var r0 models.ListGameLibraryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) models.ListGameLibraryResponse); ok {
		r0 = rf(ctx, userID, cursor)
	} else {
		r0 = ret.Get(0).(models.ListGameLibraryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *DocumentStore) ListStarredGames(ctx context.Context, userID uuid.UUID, cursor string) (models.ListGameLibraryResponse, error) {
	ret := _m.Called(ctx, userID, cursor)

	if len(ret) == 0 {
		panic("no return value specified for ListStarredGames")
	}

	var r0 models.ListGameLibraryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) models.ListGameLibraryResponse); ok {
		r0 = rf(ctx, userID, cursor)
	} else {
		r0 = ret.Get(0).(models.ListGameLibraryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, userID, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *DocumentStore) SetDocumentVisibility(ctx context.Context, documentID uuid.UUID, userID uuid.UUID, isPublic bool) (models.DocumentSummary, error) {
	ret := _m.Called(ctx, documentID, userID, isPublic)

	if len(ret) == 0 {
		panic("no return value specified for SetDocumentVisibility")
	}

	var r0 models.DocumentSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) models.DocumentSummary); ok {
		r0 = rf(ctx, documentID, userID, isPublic)
	} else {
		r0 = ret.Get(0).(models.DocumentSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r1 = rf(ctx, documentID, userID, isPublic)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *DocumentStore) StarGame(ctx context.Context, documentID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, documentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for StarGame")
	}

	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		return rf(ctx, documentID, userID)
	}

	return ret.Error(0)
}

func (_m *DocumentStore) UnstarGame(ctx context.Context, documentID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, documentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnstarGame")
	}

	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		return rf(ctx, documentID, userID)
	}

	return ret.Error(0)
}

func (_m *DocumentStore) ListDocumentChapters(ctx context.Context, documentID uuid.UUID, userID uuid.UUID) ([]models.ChapterSummary, error) {
	ret := _m.Called(ctx, documentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListDocumentChapters")
	}

	var r0 []models.ChapterSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.ChapterSummary); ok {
		r0 = rf(ctx, documentID, userID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.ChapterSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, documentID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *DocumentStore) ListChapterSubChapters(ctx context.Context, chapterID uuid.UUID, userID uuid.UUID) ([]models.SubChapterSummary, error) {
	ret := _m.Called(ctx, chapterID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListChapterSubChapters")
	}

	var r0 []models.SubChapterSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.SubChapterSummary); ok {
		r0 = rf(ctx, chapterID, userID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]models.SubChapterSummary)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, chapterID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *DocumentStore) LoadUserDocument(ctx context.Context, documentID uuid.UUID, userID uuid.UUID) (models.Document, error) {
	ret := _m.Called(ctx, documentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LoadUserDocument")
	}

	var r0 models.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.Document); ok {
		r0 = rf(ctx, documentID, userID)
	} else {
		r0 = ret.Get(0).(models.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, documentID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *DocumentStore) DeleteDocumentCascade(ctx context.Context, documentID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, documentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocumentCascade")
	}

	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		return rf(ctx, documentID, userID)
	}

	return ret.Error(0)
}

func NewDocumentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *DocumentStore {
	mock := &DocumentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
