// Code generated by mockery; DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
)

type Publisher struct {
	mock.Mock
}

func (_m *Publisher) Publish(ctx context.Context, messageID string, value any) error {
	ret := _m.Called(ctx, messageID, value)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	if rf, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		return rf(ctx, messageID, value)
	}

	return ret.Error(0)
}

func NewPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Publisher {
	mock := &Publisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
