// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "skybloom/document-content-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockSourceUploader is an autogenerated mock type for the SourceUploader type
type MockSourceUploader struct {
	mock.Mock
}

// UploadSource provides a mock function with given fields: ctx, content, userID, documentID, filename, contentType
func (_m *MockSourceUploader) UploadSource(ctx context.Context, content []byte, userID string, documentID string, filename string, contentType string) (models.SourceRef, error) {
	ret := _m.Called(ctx, content, userID, documentID, filename, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadSource")
	}

	var r0 models.SourceRef
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string, string, string) (models.SourceRef, error)); ok {
		return rf(ctx, content, userID, documentID, filename, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string, string, string) models.SourceRef); ok {
		r0 = rf(ctx, content, userID, documentID, filename, contentType)
	} else {
		r0 = ret.Get(0).(models.SourceRef)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, string, string, string, string) error); ok {
		r1 = rf(ctx, content, userID, documentID, filename, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDocumentAssets provides a mock function with given fields: ctx, document
func (_m *MockSourceUploader) DeleteDocumentAssets(ctx context.Context, document models.Document) error {
	ret := _m.Called(ctx, document)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocumentAssets")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Document) error); ok {
		r0 = rf(ctx, document)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockSourceUploader creates a new instance of MockSourceUploader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSourceUploader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSourceUploader {
	mock := &MockSourceUploader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
