// Code generated by mockery; DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"skybloom/document-content-api/internal/models"
)

type StorageClient struct {
	mock.Mock
}

func (_m *StorageClient) UploadSource(ctx context.Context, content []byte, userID string, documentID string, filename string, contentType string) (models.SourceRef, error) {
	ret := _m.Called(ctx, content, userID, documentID, filename, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadSource")
	}

	var r0 models.SourceRef
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, string, string, string, string) models.SourceRef); ok {
		r0 = rf(ctx, content, userID, documentID, filename, contentType)
	} else {
		r0 = ret.Get(0).(models.SourceRef)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, string, string, string, string) error); ok {
		r1 = rf(ctx, content, userID, documentID, filename, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func (_m *StorageClient) DeleteDocumentFiles(ctx context.Context, document models.Document) error {
	ret := _m.Called(ctx, document)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDocumentFiles")
	}

	if rf, ok := ret.Get(0).(func(context.Context, models.Document) error); ok {
		return rf(ctx, document)
	}

	return ret.Error(0)
}

func NewStorageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageClient {
	mock := &StorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
