// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "skybloom/document-content-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockTaskStatusStore is an autogenerated mock type for the TaskStatusStore type
type MockTaskStatusStore struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, taskID
func (_m *MockTaskStatusStore) Get(ctx context.Context, taskID string) (models.TaskStatus, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.TaskStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.TaskStatus, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.TaskStatus); ok {
		r0 = rf(ctx, taskID)
	} else {
		r0 = ret.Get(0).(models.TaskStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, status
func (_m *MockTaskStatusStore) Set(ctx context.Context, status models.TaskStatus) error {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.TaskStatus) error); ok {
		r0 = rf(ctx, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockTaskStatusStore creates a new instance of MockTaskStatusStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskStatusStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskStatusStore {
	mock := &MockTaskStatusStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
