// Code generated by mockery; DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"

	"skybloom/document-content-api/internal/models"
)

type TaskStatusStore struct {
	mock.Mock
}

func (_m *TaskStatusStore) Set(ctx context.Context, status models.TaskStatus) error {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	if rf, ok := ret.Get(0).(func(context.Context, models.TaskStatus) error); ok {
		return rf(ctx, status)
	}

	return ret.Error(0)
}

func (_m *TaskStatusStore) Get(ctx context.Context, taskID string) (models.TaskStatus, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.TaskStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) models.TaskStatus); ok {
		r0 = rf(ctx, taskID)
	} else {
		r0 = ret.Get(0).(models.TaskStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

func NewTaskStatusStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskStatusStore {
	mock := &TaskStatusStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
