services:
  document-content-api:
    container_name: document-content-api
    build:
      context: ./src/api
      dockerfile: Dockerfile
    image: document-content-api:latest
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - ./temp:/temp

  document-content-grpc:
    container_name: document-content-grpc
    build:
      context: ./src/grpc
      dockerfile: Dockerfile
    image: document-content-grpc:latest
    ports:
      - "50051:50051"
    env_file:
      - .env
  document-content-worker:
    container_name: document-content-worker
    hostname: document-content-worker
    build:
      context: ./src/worker
      dockerfile: Dockerfile
    image: document-content-worker:latest
    command: python -m app.rabbitmq_worker
    env_file:
      - .env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./src/worker:/app
      - ./output:/output
      - ./temp:/temp
      - models:/root/.paddlex
      - /usr/lib/wsl/lib:/usr/lib/wsl/lib
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
volumes:
  models:
