services:
  document-content-worker:
    env_file:
      - ../../.env.local
    volumes:
      - ./src/worker:/app
      - ./output:/output
      - ./temp:/temp
      - models:/root/.paddlex
      - /usr/lib/wsl/lib:/usr/lib/wsl/lib

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    ports:
      - "6379:6379"
