services:
  document-content-worker:
    container_name: document-content-worker
    hostname: document-content-worker
    build:
      context: ./src/worker
      dockerfile: Dockerfile
    image: document-content-worker:latest
    command: python -m app.rabbitmq_worker
    env_file:
      - .env
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    volumes:
      - ./src/worker:/app
      - ./output:/output
      - ./temp:/temp
      - models:/root/.paddlex
      - /usr/lib/wsl/lib:/usr/lib/wsl/lib
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    restart: unless-stopped

volumes:
  models:
