// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	repository "skybloom/document-content-grpc/internal/repository"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockDocumentRepository is an autogenerated mock type for the DocumentRepository type
type MockDocumentRepository struct {
	mock.Mock
}

// LoadDocumentRow provides a mock function with given fields: ctx, subChapterID, userID
func (_m *MockDocumentRepository) LoadDocumentRow(ctx context.Context, subChapterID uuid.UUID, userID uuid.UUID) (repository.DocumentRow, error) {
	ret := _m.Called(ctx, subChapterID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LoadDocumentRow")
	}

	var r0 repository.DocumentRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (repository.DocumentRow, error)); ok {
		return rf(ctx, subChapterID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) repository.DocumentRow); ok {
		r0 = rf(ctx, subChapterID, userID)
	} else {
		r0 = ret.Get(0).(repository.DocumentRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, subChapterID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockDocumentRepository creates a new instance of MockDocumentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocumentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocumentRepository {
	mock := &MockDocumentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
