// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMarkdownLoader is an autogenerated mock type for the MarkdownLoader type
type MockMarkdownLoader struct {
	mock.Mock
}

// Download provides a mock function with given fields: ctx, bucket, key
func (_m *MockMarkdownLoader) Download(ctx context.Context, bucket string, key string) (string, error) {
	ret := _m.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, bucket, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, bucket, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, bucket, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockMarkdownLoader creates a new instance of MockMarkdownLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMarkdownLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMarkdownLoader {
	mock := &MockMarkdownLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
